name: SL Scan

on: push

jobs:
  Scan-Build:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: slscan_report  

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        path: reports
